#!/usr/bin/env python3
"""Does an indexed anchor still save you on a super-node? (degree-distribution axis)

The scale curve in this experiment concluded that a label-anchored, index-seeking plan
holds **constant db hits at every scale factor** while an unlabeled one grows linearly,
and the memory sweeps then found no page-cache cliff because "the working set is 25
pages and they stay hot". Both conclusions were measured on a graph generated by uniform
random attachment, whose degree distribution turned out to be binomial: mean 10, **max
31** at SF1000. That graph has no hubs at all.

Real payment graphs do, and LDBC FinBench treats that as its defining difference from
the social-network benchmark: "the degree of hub vertices ... may scale up to millions
in large data scales ... The higher degree of hub vertices poses new challenges to the
performance of systems."

The mechanism at stake is precise. An index seek finds a node in O(1) regardless of its
degree — that part survives. But *expanding* it costs O(degree), and a 2-hop expansion
costs O(degree x neighbour degree). So on a hub the anchor stops being the thing that
determines cost, and the tuned/naive distinction this experiment is built on may
collapse. Whether it does is an empirical question, which is what this probe answers.

Three query arms per degree band, all returning the same kind of answer:

``final_limit``
    Untruncated 2-hop with ``LIMIT`` only at the end. This is the shape SEOCHO's
    guardrail currently produces — ``max_result_rows`` bounds the *result*, not the
    *intermediate expansion*, so it cannot bound work on a hub.

``truncated``
    FinBench's own answer: per-hop truncation. ``TRUNCATION_LIMIT`` with
    ``TRUNCATION_ORDER`` (``TIMESTAMP_DESCENDING`` by default) makes a traversal use only
    the K most recent edges, which the spec describes as "a deterministic sampling in
    traversing". Same anchor, bounded work.

``unbounded_count``
    The full 2-hop count, as an upper bound on what the other two are avoiding.

Usage:
    python scripts/finbench/hub_degree_probe.py --database finbenchsf1000hub \
        --manifest outputs/finbench/sf1000-hub/manifest.json \
        --password "$NEO4J_PASSWORD" --out outputs/finbench/hub_degree.json
"""

from __future__ import annotations

import argparse
import importlib.util
import json
import statistics
import time
from pathlib import Path
from typing import Any, Dict, List

_HERE = Path(__file__).resolve().parent


def _load(name: str, filename: str):
    spec = importlib.util.spec_from_file_location(name, _HERE / filename)
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)  # type: ignore[union-attr]
    return mod


protocol = _load("finbench_bench_protocol", "bench_protocol.py")

# Truncation depth. FinBench's illustrative figure is "the 5,000 most recent edges";
# we keep that so the arm is comparable to the published mechanism rather than tuned
# to flatter this graph.
TRUNCATION_LIMIT = 5000

ARMS: Dict[str, str] = {
    # What the middleware emits today: the bound sits after all the work is done.
    "final_limit": """
        MATCH (a:Account {id: $id})-[:TRANSFER]->(b:Account)-[:TRANSFER]->(c:Account)
        RETURN DISTINCT c.id AS id
        LIMIT $limit
    """,
    # What FinBench prescribes: bound each expansion, ordered by timestamp so the
    # sample is deterministic and defensible rather than arbitrary.
    "truncated": """
        MATCH (a:Account {id: $id})-[r1:TRANSFER]->(b:Account)
        WITH b, r1.ts AS ts1 ORDER BY ts1 DESC LIMIT $trunc
        MATCH (b)-[r2:TRANSFER]->(c:Account)
        WITH c, r2.ts AS ts2 ORDER BY ts2 DESC LIMIT $trunc
        RETURN DISTINCT c.id AS id
        LIMIT $limit
    """,
    # Upper bound: how much work the graph actually contains behind this anchor.
    "unbounded_count": """
        MATCH (a:Account {id: $id})-[:TRANSFER]->(b:Account)-[:TRANSFER]->(c:Account)
        RETURN count(DISTINCT c) AS n
    """,
}


def _db_hits(plan: Dict[str, Any]) -> int:
    total = int(plan.get("dbHits", 0) or 0)
    for child in plan.get("children", []) or []:
        total += _db_hits(child)
    return total


def _operators(plan: Dict[str, Any], acc: List[str] | None = None) -> List[str]:
    acc = acc if acc is not None else []
    op = plan.get("operatorType")
    if op:
        acc.append(op.split("@")[0])
    for child in plan.get("children", []) or []:
        _operators(child, acc)
    return acc


def measure_arm(driver, database: str, cypher: str, params: Dict[str, Any],
                repeats: int, timeout_s: float) -> Dict[str, Any]:
    """Measure one arm, treating a timeout as a result rather than a crash.

    On a hub the unbounded arms are not merely slow, they are the failure being
    measured — so a wall-clock ceiling is part of the instrument. Recording
    ``timed_out`` keeps a run that blows past the ceiling in the table as a bounded
    lower bound instead of dropping the row (or hanging the sweep).
    """
    from neo4j.exceptions import Neo4jError

    def _run(session, text: str):
        # The ceiling has to go on the transaction. ``session.run(..., timeout=x)``
        # looks like it sets one but does not: Session.run forwards every keyword to
        # the *query parameters*, so a `timeout` kwarg silently becomes an unused
        # parameter and the query runs unbounded. An earlier version of this probe did
        # exactly that, and the ">60s" it reported actually came from the server's
        # db.transaction.timeout — a real ceiling, but not the one the flag claimed.
        t0 = time.perf_counter()
        tx = session.begin_transaction(timeout=timeout_s)
        try:
            result = tx.run(text, **params)
            rows = list(result)
            summary = result.consume()
            tx.commit()
        except BaseException:
            tx.close()
            raise
        return rows, summary, (time.perf_counter() - t0) * 1000.0

    with driver.session(database=database) as session:
        try:
            rows, summary, _ = _run(session, "PROFILE " + cypher)
        except Neo4jError as exc:
            return {"timed_out": True, "limit_s": timeout_s, "error": exc.code,
                    "db_hits": None, "rows": None, "answer": None,
                    "index_seek": None, "scan": None,
                    "cold_ms": None, "p50_ms": None, "p99_ms": None}
        plan = summary.profile or {}
        hits = _db_hits(plan)
        ops = _operators(plan)

        try:
            _, _, cold_ms = _run(session, cypher)
            samples = []
            for _ in range(repeats):
                _, _, elapsed = _run(session, cypher)
                samples.append(elapsed)
        except Neo4jError as exc:
            return {"timed_out": True, "limit_s": timeout_s, "error": exc.code,
                    "db_hits": hits, "rows": len(rows), "answer": None,
                    "index_seek": any(o.startswith("NodeIndexSeek") for o in ops),
                    "scan": any(o in ("AllNodesScan", "NodeByLabelScan") for o in ops),
                    "cold_ms": None, "p50_ms": None, "p99_ms": None}

    samples.sort()
    return {
        "timed_out": False,
        "db_hits": hits,
        "rows": len(rows),
        "answer": rows[0].get("n") if rows and "n" in rows[0] else None,
        # An index seek on the anchor is what the tuned-plan claim rests on; record
        # whether it survived so a cost change can be attributed to expansion rather
        # than to the planner silently giving up on the index.
        "index_seek": any(o.startswith("NodeIndexSeek") for o in ops),
        "scan": any(o in ("AllNodesScan", "NodeByLabelScan") for o in ops),
        "cold_ms": round(cold_ms, 2),
        "p50_ms": round(statistics.median(samples), 2),
        "p99_ms": round(samples[min(len(samples) - 1, int(len(samples) * 0.99))], 2),
    }


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--database", required=True)
    parser.add_argument("--manifest", type=Path, required=True,
                        help="snapshot manifest; supplies degree_profile.curated_anchors")
    parser.add_argument("--uri", default="bolt://localhost:7687")
    parser.add_argument("--user", default="neo4j")
    parser.add_argument("--password", default="")
    parser.add_argument("--repeats", type=int, default=5)
    parser.add_argument("--limit", type=int, default=50,
                        help="final row limit; mirrors the guardrail's max_result_rows")
    parser.add_argument("--query-timeout", type=float, default=90.0,
                        help="per-query ceiling in seconds; an arm that exceeds it is "
                             "recorded as timed_out rather than dropped or left hanging")
    parser.add_argument("--no-warmup", action="store_true")
    parser.add_argument("--out", type=Path)
    args = parser.parse_args()

    from neo4j import GraphDatabase

    with args.manifest.open('r', encoding='utf-8') as f:

        manifest = json.load(f)
    profile = manifest.get("degree_profile") or {}
    anchors = profile.get("curated_anchors") or []
    if not anchors:
        raise SystemExit(
            f"{args.manifest} has no degree_profile.curated_anchors — regenerate the "
            "snapshot with the current generator so anchors are curated by degree band")

    driver = GraphDatabase.driver(args.uri, auth=(args.user, args.password))
    try:
        warm = None if args.no_warmup else protocol.warm_up(driver, args.database)
        results: List[Dict[str, Any]] = []
        for anchor in anchors:
            for arm, cypher in ARMS.items():
                params = {"id": f"Account:{anchor['account_id']}",
                          "limit": args.limit, "trunc": TRUNCATION_LIMIT}
                measured = measure_arm(driver, args.database, cypher, params,
                                       args.repeats, args.query_timeout)
                results.append({"band": anchor["band"], "degree": anchor["degree"],
                                "account_id": anchor["account_id"], "arm": arm,
                                **measured})
                hits, p50 = measured["db_hits"], measured["p50_ms"]
                print(f"[hub] {anchor['band']:8s} deg={anchor['degree']:>7,} "
                      f"{arm:16s} hits={'—' if hits is None else format(hits, ','):>12} "
                      f"p50={'TIMEOUT' if p50 is None else format(p50, ',.1f') + 'ms':>11} "
                      f"seek={measured['index_seek']}", flush=True)
    finally:
        driver.close()

    report = {
        "schema_version": "seocho.finbench.hub-degree.v1",
        "database": args.database,
        "hub_skew": manifest.get("hub_skew"),
        "truncation_limit": TRUNCATION_LIMIT,
        "final_limit": args.limit,
        "warm_up": (warm or {}).get("method"),
        "degree_profile": {k: v for k, v in profile.items() if k != "curated_anchors"},
        "results": results,
    }

    lines = [
        "# Does an indexed anchor still save you on a super-node?", "",
        f"database `{args.database}` · hub_skew {manifest.get('hub_skew')} · "
        f"degree mean {profile.get('mean')} / max {profile.get('max'):,} "
        f"(max/mean {profile.get('max_over_mean'):,})", "",
        f"`truncated` applies FinBench-style per-hop truncation at {TRUNCATION_LIMIT:,} "
        f"edges ordered by timestamp descending; `final_limit` is the shape the guardrail "
        f"emits today, bounding only the result at {args.limit} rows.", "",
        "| band | degree | arm | db hits | rows | index seek | cold | p50 | p99 |",
        "|---|---|---|---|---|---|---|---|---|",
    ]
    def _ms(v):
        return f"**>{args.query_timeout:.0f}s**" if v is None else f"{v:,.1f}ms"

    for r in results:
        lines.append(
            f"| {r['band']} | {r['degree']:,} | {r['arm']} | "
            f"{'—' if r['db_hits'] is None else format(r['db_hits'], ',')} | "
            f"{'—' if r['rows'] is None else r['rows']} | "
            f"{'—' if r['index_seek'] is None else ('yes' if r['index_seek'] else 'NO')} | "
            f"{_ms(r['cold_ms'])} | {_ms(r['p50_ms'])} | {_ms(r['p99_ms'])} |")
    markdown = "\n".join(lines) + "\n"

    if args.out:
        args.out.parent.mkdir(parents=True, exist_ok=True)
        args.out.write_text(json.dumps(report, indent=2) + "\n")
        args.out.with_suffix(".md").write_text(markdown)
    print(markdown)


if __name__ == "__main__":
    main()
