"""
Project configuration file — .seocho.toml

Reads project-level defaults so CLI commands don't need repeated flags.

If ``.seocho.toml`` exists in the current directory (or parents),
CLI commands use its values as defaults::

    # .seocho.toml
    [project]
    schema = "schema.jsonld"
    database = "news_kg"

    [neo4j]
    uri = "bolt://localhost:7687"
    user = "neo4j"
    password = "password"

    [llm]
    model = "gpt-4o"

Then ``seocho index ./data/`` just works — no flags needed.
"""

from __future__ import annotations

import logging
from pathlib import Path
from typing import Any, Dict, Optional

logger = logging.getLogger(__name__)

CONFIG_FILENAME = ".seocho.toml"


def find_config(start: Optional[Path] = None) -> Optional[Path]:
    """Walk up from ``start`` looking for .seocho.toml."""
    current = (start or Path.cwd()).resolve()
    for parent in [current, *current.parents]:
        candidate = parent / CONFIG_FILENAME
        if candidate.is_file():
            return candidate
    return None


def load_config(path: Optional[Path] = None) -> Dict[str, Any]:
    """Load .seocho.toml and return as nested dict.

    Returns empty dict if file not found or Python < 3.11 (no tomllib).
    """
    config_path = path or find_config()
    if config_path is None:
        return {}

    try:
        text = config_path.read_text(encoding="utf-8")
    except OSError:
        return {}

    # Python 3.11+ has tomllib; 3.10 needs fallback
    try:
        import tomllib
        return tomllib.loads(text)
    except ImportError:
        pass

    # Fallback: simple key=value parser for the subset we need
    try:
        return _simple_toml_parse(text)
    except Exception:
        logger.warning("Could not parse %s", config_path)
        return {}


def get_default(config: Dict[str, Any], section: str, key: str, fallback: Any = None) -> Any:
    """Get a value from config with section.key path."""
    return config.get(section, {}).get(key, fallback)


def write_config(
    path: Path,
    *,
    schema: str = "schema.jsonld",
    database: str = "neo4j",
    neo4j_uri: str = "bolt://localhost:7687",
    neo4j_user: str = "neo4j",
    neo4j_password: str = "password",
    model: str = "gpt-4o",
) -> None:
    """Write a .seocho.toml file."""
    content = f'''# SEOCHO project configuration
# Generated by `seocho init`

[project]
schema = "{schema}"
database = "{database}"

[neo4j]
uri = "{neo4j_uri}"
user = "{neo4j_user}"
password = "{neo4j_password}"

[llm]
model = "{model}"
'''
    path.write_text(content, encoding="utf-8")


def _simple_toml_parse(text: str) -> Dict[str, Any]:
    """Minimal TOML parser for section.key = "value" patterns."""
    result: Dict[str, Any] = {}
    current_section = ""
    for line in text.splitlines():
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        if line.startswith("[") and line.endswith("]"):
            current_section = line[1:-1].strip()
            result.setdefault(current_section, {})
            continue
        if "=" in line:
            key, _, value = line.partition("=")
            key = key.strip()
            value = value.strip().strip('"').strip("'")
            if current_section:
                result.setdefault(current_section, {})[key] = value
            else:
                result[key] = value
    return result
