from importlib.metadata import PackageNotFoundError, version

from .api import (
    add,
    add_with_details,
    agents,
    apply_artifact,
    ask,
    chat,
    close,
    configure,
    connect,
    databases,
    debate,
    delete,
    ensure_fulltext_indexes,
    get,
    get_client,
    graphs,
    health,
    platform_chat,
    raw_ingest,
    reset_session,
    router,
    search,
    semantic,
    session_history,
)
from .client import AsyncSeocho, Seocho
from .exceptions import SeochoConnectionError, SeochoError, SeochoHTTPError
from .governance import ArtifactDiff, ArtifactValidationMessage, ArtifactValidationResult
from .local import LocalRuntimeStatus
from .semantic import (
    ApprovedArtifacts,
    KnownEntity,
    OntologyCandidate,
    OntologyClass,
    OntologyProperty,
    OntologyRelationship,
    SemanticArtifact,
    SemanticArtifactDraftInput,
    SemanticArtifactSummary,
    SemanticPromptContext,
    ShaclCandidate,
    ShaclPropertyConstraint,
    ShaclShape,
    VocabularyCandidate,
    VocabularyTerm,
)
from .types import (
    AgentRunResponse,
    ArchiveResult,
    ChatResponse,
    DebateRunResponse,
    EntityOverride,
    FulltextIndexResponse,
    GraphTarget,
    Memory,
    MemoryCreateResult,
    PlatformChatResponse,
    PlatformSessionResponse,
    RawIngestError,
    RawIngestResult,
    RawIngestWarning,
    SearchResponse,
    SearchResult,
    SemanticRunResponse,
)

try:
    __version__ = version("seocho")
except PackageNotFoundError:
    __version__ = "0.1.0"

__all__ = [
    "ApprovedArtifacts",
    "AgentRunResponse",
    "ArtifactDiff",
    "ArtifactValidationMessage",
    "ArtifactValidationResult",
    "ArchiveResult",
    "AsyncSeocho",
    "ChatResponse",
    "DebateRunResponse",
    "EntityOverride",
    "FulltextIndexResponse",
    "GraphTarget",
    "KnownEntity",
    "LocalRuntimeStatus",
    "Memory",
    "MemoryCreateResult",
    "OntologyCandidate",
    "OntologyClass",
    "OntologyProperty",
    "OntologyRelationship",
    "PlatformChatResponse",
    "PlatformSessionResponse",
    "RawIngestError",
    "RawIngestResult",
    "RawIngestWarning",
    "SearchResponse",
    "SearchResult",
    "SemanticRunResponse",
    "SemanticArtifact",
    "SemanticArtifactDraftInput",
    "SemanticArtifactSummary",
    "SemanticPromptContext",
    "Seocho",
    "SeochoConnectionError",
    "SeochoError",
    "SeochoHTTPError",
    "ShaclCandidate",
    "ShaclPropertyConstraint",
    "ShaclShape",
    "VocabularyCandidate",
    "VocabularyTerm",
    "__version__",
    "add",
    "add_with_details",
    "agents",
    "apply_artifact",
    "ask",
    "chat",
    "close",
    "configure",
    "connect",
    "databases",
    "debate",
    "delete",
    "ensure_fulltext_indexes",
    "get",
    "get_client",
    "graphs",
    "health",
    "platform_chat",
    "raw_ingest",
    "reset_session",
    "router",
    "search",
    "semantic",
    "session_history",
]
