from importlib.metadata import PackageNotFoundError, version

from .api import (
    advanced,
    add,
    add_with_details,
    agents,
    apply_artifact,
    ask,
    chat,
    close,
    configure,
    connect,
    databases,
    debate,
    delete,
    ensure_fulltext_indexes,
    execute,
    get,
    get_client,
    graphs,
    health,
    plan,
    platform_chat,
    raw_ingest,
    react,
    reset_session,
    router,
    search,
    semantic,
    session_history,
)
from .client import AsyncSeocho, ExecutionPlanBuilder, Seocho
from .exceptions import SeochoConnectionError, SeochoError, SeochoHTTPError
from .governance import ArtifactDiff, ArtifactValidationMessage, ArtifactValidationResult
from .indexing import BatchIndexingResult, IndexingResult
from .local import LocalRuntimeStatus
from .vector_store import VectorSearchResult
from .ontology import Cardinality, NodeDef, Ontology, P, PropertyType, RelDef
from .semantic import (
    ApprovedArtifacts,
    KnownEntity,
    OntologyCandidate,
    OntologyClass,
    OntologyProperty,
    OntologyRelationship,
    SemanticArtifact,
    SemanticArtifactDraftInput,
    SemanticArtifactSummary,
    SemanticPromptContext,
    ShaclCandidate,
    ShaclPropertyConstraint,
    ShaclShape,
    VocabularyCandidate,
    VocabularyTerm,
)
from .models import (
    AgentRunResponse,
    ArchiveResult,
    ChatResponse,
    DebateRunResponse,
    EvidenceBundle,
    EntityOverride,
    ExecutionPlan,
    ExecutionResult,
    FulltextIndexResponse,
    GraphRef,
    GraphTarget,
    Memory,
    MemoryCreateResult,
    PlatformChatResponse,
    PlatformSessionResponse,
    RawIngestError,
    RawIngestResult,
    RawIngestWarning,
    ReasoningPolicy,
    SearchResponse,
    SearchResult,
    SemanticRunResponse,
    RunMetadata,
    StrategyDecision,
    SupportAssessment,
)

try:
    __version__ = version("seocho")
except PackageNotFoundError:
    __version__ = "0.1.0"

__all__ = [
    # --- Ontology-first SDK primitives ---
    "Ontology",
    "NodeDef",
    "RelDef",
    "P",
    "PropertyType",
    "Cardinality",
    # --- Client ---
    "Seocho",
    "AsyncSeocho",
    "ExecutionPlanBuilder",
    # --- Exceptions ---
    "SeochoError",
    "SeochoConnectionError",
    "SeochoHTTPError",
    # --- Semantic artifact types ---
    "ApprovedArtifacts",
    "KnownEntity",
    "OntologyCandidate",
    "OntologyClass",
    "OntologyProperty",
    "OntologyRelationship",
    "SemanticArtifact",
    "SemanticArtifactDraftInput",
    "SemanticArtifactSummary",
    "SemanticPromptContext",
    "ShaclCandidate",
    "ShaclPropertyConstraint",
    "ShaclShape",
    "VocabularyCandidate",
    "VocabularyTerm",
    # --- Governance ---
    "ArtifactDiff",
    "ArtifactValidationMessage",
    "ArtifactValidationResult",
    # --- Response types ---
    "AgentRunResponse",
    "ArchiveResult",
    "ChatResponse",
    "DebateRunResponse",
    "EvidenceBundle",
    "EntityOverride",
    "ExecutionPlan",
    "ExecutionResult",
    "FulltextIndexResponse",
    "GraphRef",
    "GraphTarget",
    "LocalRuntimeStatus",
    "Memory",
    "MemoryCreateResult",
    "PlatformChatResponse",
    "PlatformSessionResponse",
    "RawIngestError",
    "RawIngestResult",
    "RawIngestWarning",
    "ReasoningPolicy",
    "RunMetadata",
    "SearchResponse",
    "SearchResult",
    "SemanticRunResponse",
    "StrategyDecision",
    "SupportAssessment",
    # --- Module-level convenience functions ---
    "__version__",
    "add",
    "add_with_details",
    "advanced",
    "agents",
    "apply_artifact",
    "ask",
    "chat",
    "close",
    "configure",
    "connect",
    "databases",
    "debate",
    "delete",
    "ensure_fulltext_indexes",
    "execute",
    "get",
    "get_client",
    "graphs",
    "health",
    "plan",
    "platform_chat",
    "raw_ingest",
    "react",
    "reset_session",
    "router",
    "search",
    "semantic",
    "session_history",
]
