"""12-pattern Cypher validator for free-form LLM output.

Closes seocho-ixsk.

Background
----------
``seocho.query.cypher_validator.CypherQueryValidator`` validates *constrained
Cypher plans* with parameter bindings (used by the agent SDK). This module
covers the complementary case: **free-form Cypher generated by an LLM** in
text2cypher contexts. Patterns and detection methods are taken verbatim from
``examples/teaching/chapter-03-cypher-failure-taxonomy.md`` (the Ch 3
appendix).

The 12 patterns are organised in 3 groups:

- **Generation**       (#1-5):  label hallucination, property typo,
                                bidirectional miss, missing LIMIT, injection
- **Execution**        (#6-9):  unbounded path, cartesian product,
                                null property crash, read-only violation
- **Silent semantic**  (#10-12): wrong relationship direction, missing DISTINCT,
                                 temporal-ignorant query

Most checks are regex-based for speed. ``#10`` and ``#12`` use very small
ontology-aware lookups instead of a full Cypher AST.

Usage
-----

::

    from seocho.query.guards import validate_cypher, CypherValidationError

    issues = validate_cypher(
        cypher,
        allowed_labels={"Company", "Risk", "Filing"},
        ontology_relationships={"HAS_RISK": ("Company", "Risk")},
        time_aware_relationships={"HAS_RISK", "OWNS"},
    )
    if any(i.severity == "block" for i in issues):
        raise CypherValidationError(issues)
"""

from __future__ import annotations

import re
from dataclasses import dataclass
from typing import Iterable, List, Mapping, Optional, Sequence, Set, Tuple


# ---------------------------------------------------------------------------
# Issue model
# ---------------------------------------------------------------------------


@dataclass(frozen=True)
class CypherIssue:
    """A single detected anti-pattern in a Cypher query."""

    code: str       # e.g. "#1-label"
    severity: str   # "block" | "warn" | "info"
    detail: str

    def __str__(self) -> str:  # pragma: no cover — display only
        return f"[{self.severity}] {self.code} {self.detail}"


class CypherValidationError(RuntimeError):
    """Raised when callers ask validator to enforce block-level issues."""

    def __init__(self, issues: Sequence[CypherIssue]) -> None:
        self.issues = list(issues)
        super().__init__(
            "cypher rejected: "
            + ", ".join(f"{i.code}({i.severity}): {i.detail}" for i in issues)
        )


# ---------------------------------------------------------------------------
# Regex catalogue
# ---------------------------------------------------------------------------


_DESTRUCTIVE_RE = re.compile(
    r"\b(CREATE|MERGE|DELETE|SET|DETACH|REMOVE|DROP)\b", re.IGNORECASE
)
_UNBOUNDED_RE = re.compile(r"\[[^\]]*\*\s*\.\.\s*\]|\[[^\]]*\*\s*\]")
_LABEL_RE = re.compile(r":(\w+)(?=\s*[{)\]])")
_PROP_RE = re.compile(r"\b([A-Za-z_]\w*)\.([A-Za-z_]\w*)\b")
_LIMIT_RE = re.compile(r"\bLIMIT\s+\d+\b", re.IGNORECASE)
_RETURN_RE = re.compile(r"\bRETURN\b", re.IGNORECASE)
_COUNT_RE = re.compile(r"\bcount\s*\(", re.IGNORECASE)
_DISTINCT_RE = re.compile(r"\bDISTINCT\b", re.IGNORECASE)
_DIRECTED_REL_RE = re.compile(r"\[[^\]]*:\s*(\w+)[^\]]*\]\s*-(>|>)")
_UNDIRECTED_REL_RE = re.compile(r"\[[^\]]*:\s*(\w+)[^\]]*\]\s*-(?![>])")
_MATCH_RE = re.compile(r"\bMATCH\s*\((.*?)\)\s*[,]\s*\(", re.IGNORECASE | re.DOTALL)
_WHERE_RE = re.compile(r"\bWHERE\b", re.IGNORECASE)
_TEMPORAL_FILTER_RE = re.compile(
    r"\b(temporal_range|valid_from|valid_until|extracted_at|published_at)\b",
    re.IGNORECASE,
)
_WRONG_DIRECTION_RE = re.compile(
    r"\(\s*[^()]*?:(\w+)[^()]*?\)\s*-\[[^\]]*:\s*(\w+)[^\]]*\]\s*->\s*\(\s*[^()]*?:(\w+)",
    re.IGNORECASE,
)


# ---------------------------------------------------------------------------
# Individual detectors
# ---------------------------------------------------------------------------


def detect_label_hallucination(
    cypher: str, allowed: Set[str]
) -> List[str]:
    if not allowed:
        return []
    return sorted({lbl for lbl in _LABEL_RE.findall(cypher) if lbl not in allowed})


def detect_property_typos(
    cypher: str, schema: Mapping[str, Set[str]]
) -> List[str]:
    """Heuristic — looks at ``var.prop`` pairs and complains when the *property*
    is not in the union of allowed property names. Avoids ontology
    type-resolution to stay cheap."""
    if not schema:
        return []
    all_props = set().union(*schema.values())
    bad: Set[str] = set()
    for var, prop in _PROP_RE.findall(cypher):
        if prop in {"name", "id"} or prop in all_props:
            continue
        bad.add(f"{var}.{prop}")
    return sorted(bad)


def detect_missing_limit(cypher: str) -> bool:
    body = cypher.strip().rstrip(";").strip()
    return bool(_RETURN_RE.search(body)) and not _LIMIT_RE.search(body)


def detect_destructive_op(cypher: str) -> Optional[str]:
    m = _DESTRUCTIVE_RE.search(cypher)
    return m.group(1).upper() if m else None


def detect_unbounded_path(cypher: str) -> bool:
    return bool(_UNBOUNDED_RE.search(cypher))


def detect_cartesian_product(cypher: str) -> bool:
    """Heuristic — multiple comma-separated patterns inside a MATCH clause
    without an obvious connector. Cheap enough to keep on by default; pairs
    nicely with a WHERE-without-binding hint."""
    if not _MATCH_RE.search(cypher):
        return False
    # If a WHERE references at least two distinct variables, treat as connected.
    where = cypher.upper().find(" WHERE ")
    if where == -1:
        return True
    where_clause = cypher[where:].upper()
    var_count = len(set(re.findall(r"\b([A-Z][A-Z0-9_]*)\.", where_clause)))
    return var_count < 2


def detect_missing_distinct_count(cypher: str) -> bool:
    return bool(_COUNT_RE.search(cypher)) and not _DISTINCT_RE.search(cypher)


def detect_wrong_direction(
    cypher: str,
    ontology_relationships: Mapping[str, Tuple[str, str]],
) -> List[str]:
    """Detect ``(:Source)-[:REL]->(:Target)`` where ontology says ``REL`` goes
    the other way. Uses a regex pass over directed edges only — undirected
    matches are treated as safe."""
    if not ontology_relationships:
        return []
    bad: List[str] = []
    # Pattern with explicit direction: (lbl1)-[:REL]->(lbl2)
    for left, rel, right in _WRONG_DIRECTION_RE.findall(cypher):
        spec = ontology_relationships.get(rel)
        if spec is None:
            continue
        src_class, dst_class = spec
        if left != src_class or right != dst_class:
            bad.append(f"({left})-[:{rel}]->({right}) expected ({src_class})-[:{rel}]->({dst_class})")
    return bad


def detect_temporal_blind(
    cypher: str, time_aware_relationships: Set[str]
) -> List[str]:
    """If the query mentions any time-aware relationship type but has no
    temporal filter, raise a warning."""
    if not time_aware_relationships:
        return []
    found = {
        rel
        for rel in time_aware_relationships
        if re.search(rf":\s*{re.escape(rel)}\b", cypher, re.IGNORECASE)
    }
    if not found:
        return []
    if _TEMPORAL_FILTER_RE.search(cypher):
        return []
    return sorted(found)


# ---------------------------------------------------------------------------
# Public entry point
# ---------------------------------------------------------------------------


def validate_cypher(
    cypher: str,
    *,
    allowed_labels: Optional[Iterable[str]] = None,
    schema: Optional[Mapping[str, Iterable[str]]] = None,
    ontology_relationships: Optional[Mapping[str, Tuple[str, str]]] = None,
    time_aware_relationships: Optional[Iterable[str]] = None,
    require_read_only: bool = True,
) -> List[CypherIssue]:
    """Run all 12 detectors and return the collected issues.

    Parameters mirror the curriculum's terminology. ``schema`` maps a class
    name to its set of allowed property names; if omitted, property typo
    detection (#2) is skipped.
    """
    issues: List[CypherIssue] = []
    body = (cypher or "").strip()
    if not body:
        return issues

    allowed_set = set(allowed_labels) if allowed_labels else set()
    schema_set = {k: set(v) for k, v in (schema or {}).items()}
    time_set = set(time_aware_relationships) if time_aware_relationships else set()
    rel_spec = dict(ontology_relationships or {})

    # #1 label hallucination
    if allowed_set:
        bad = detect_label_hallucination(body, allowed_set)
        if bad:
            issues.append(CypherIssue("#1-label", "block", f"unknown labels: {bad}"))

    # #2 property typo (heuristic)
    if schema_set:
        bad = detect_property_typos(body, schema_set)
        if bad:
            issues.append(CypherIssue("#2-property", "warn", f"likely typos: {bad[:5]}"))

    # #3 bidirectional miss — informational; needs ontology hint
    # (skipped unless ontology marks rel as bidirectional — out of scope)

    # #4 LIMIT missing
    if detect_missing_limit(body):
        issues.append(CypherIssue("#4-limit", "warn", "no LIMIT clause"))

    # #5 injection / write op
    if (op := detect_destructive_op(body)) and require_read_only:
        issues.append(CypherIssue("#5-injection", "block", f"destructive op: {op}"))

    # #6 unbounded path
    if detect_unbounded_path(body):
        issues.append(CypherIssue("#6-unbounded", "block", "unbounded variable-length path"))

    # #7 cartesian product (heuristic)
    if detect_cartesian_product(body):
        issues.append(CypherIssue("#7-cartesian", "warn", "comma-separated MATCH without obvious connector"))

    # #8 null property crash — runtime-only, skipped here
    # #9 read-only violation = #5 in our taxonomy

    # #10 wrong relationship direction
    if rel_spec:
        bad = detect_wrong_direction(body, rel_spec)
        if bad:
            issues.append(CypherIssue("#10-direction", "block", "; ".join(bad)))

    # #11 missing DISTINCT around count()
    if detect_missing_distinct_count(body):
        issues.append(CypherIssue("#11-distinct", "warn", "count() without DISTINCT"))

    # #12 temporal blind
    if time_set:
        blind = detect_temporal_blind(body, time_set)
        if blind:
            issues.append(
                CypherIssue(
                    "#12-temporal", "warn",
                    f"time-aware relationships without temporal filter: {blind}",
                )
            )

    return issues


__all__ = [
    "CypherIssue",
    "CypherValidationError",
    "validate_cypher",
    "detect_label_hallucination",
    "detect_property_typos",
    "detect_missing_limit",
    "detect_destructive_op",
    "detect_unbounded_path",
    "detect_cartesian_product",
    "detect_missing_distinct_count",
    "detect_wrong_direction",
    "detect_temporal_blind",
]
