#!/usr/bin/env python3
"""Category-database federation runner for hq-42k.

This runner exercises the topology the federation scenario is meant to test:
one DozerDB DBMS, category-scoped databases, and provider/model provenance as
node properties inside each category database.  It uses the routing policy
generated by ``16_generate_federation_agent_design.py`` to select evidence,
then calls MiniMax-M2.7 as the Graph-CoT selector and grounded synthesizer.
"""
from __future__ import annotations

import argparse
import json
import os
import sys
import time
from collections import defaultdict
from dataclasses import dataclass
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

MDM_ROOT = Path(__file__).resolve().parent
ROOT = MDM_ROOT.parents[1]
for path in (MDM_ROOT, ROOT, ROOT / "scripts" / "benchmarks"):
    if str(path) not in sys.path:
        sys.path.insert(0, str(path))

from dotenv import dotenv_values  # noqa: E402

for key, value in dotenv_values(ROOT / ".env").items():
    if value is not None:
        os.environ.setdefault(key, value)

from examples.finder.lib import bench_common as bc, llm_io  # noqa: E402
from finder_4arm_sample import _ANSWER_SYSTEM, evaluate_answer  # noqa: E402
from finder_compare_vector_graph import token_f1  # noqa: E402

from examples.mdm.agents.contracts import ABSTAIN_MARK  # noqa: E402
from examples.mdm.lib import federation  # noqa: E402
from examples.mdm.lib.survivorship import SourceFact, load_ruleset, survive_numeric  # noqa: E402

INFRA = set(federation.INFRA_LABELS)
PROVIDERS = ("deepseek", "gptoss", "minimax25", "minimax27")


@dataclass(frozen=True)
class EvidenceBundle:
    selected_providers: tuple[str, ...]
    provider_contexts: dict[str, str]
    provider_fact_counts: dict[str, int]
    provider_node_counts: dict[str, int]
    survivorship: dict[str, Any] | None
    context_chars: int
    retrieval_ms: float


def evaluate_both(expected: str, answer: str) -> dict[str, Any]:
    metrics = evaluate_answer(expected, answer or "")
    metrics["token_f1"] = token_f1(answer or "", expected or "")
    return metrics


def select_providers_for_policy(
    category_policy: dict[str, Any],
    provider_presence: dict[str, dict[str, int]],
) -> list[str]:
    """Deterministic selector over category DB evidence counts.

    The LLM selector can only narrow this list; it cannot invent providers not
    present in the category database for the case.
    """
    mode = category_policy["routing_mode"]
    primary = category_policy["primary_provider"]
    scores = category_policy.get("provider_scores") or {}
    available = {
        provider
        for provider, counts in provider_presence.items()
        if counts.get("nodes", 0) > 0 or counts.get("facts", 0) > 0
    }
    if not available:
        return []

    def by_score(provider: str) -> tuple[float, int, str]:
        counts = provider_presence.get(provider, {})
        return (
            float(scores.get(provider, 0.0)),
            int(counts.get("facts", 0)) + int(counts.get("nodes", 0)),
            provider,
        )

    if mode == "category_db_best_provider_primary":
        ordered = [primary] if primary in available else []
        ordered.extend(
            provider
            for provider in sorted(available - set(ordered), key=by_score, reverse=True)
        )
        return ordered[:2] if len(ordered) > 1 else ordered

    if mode == "category_db_best_provider_then_fact_union":
        selected = [primary] if primary in available else []
        fact_providers = [
            provider
            for provider, counts in provider_presence.items()
            if provider in available and counts.get("facts", 0) > 0 and provider not in selected
        ]
        selected.extend(sorted(fact_providers, key=by_score, reverse=True))
        if not selected:
            selected = sorted(available, key=by_score, reverse=True)[:2]
        return selected

    if mode == "category_db_survivorship_first":
        fact_providers = [
            provider
            for provider, counts in provider_presence.items()
            if provider in available and counts.get("facts", 0) > 0
        ]
        return sorted(fact_providers or available, key=by_score, reverse=True)

    return sorted(available, key=by_score, reverse=True)


def _load_indexer():
    import importlib.util

    spec = importlib.util.spec_from_file_location(
        "idx_providers", MDM_ROOT / "11_index_providers.py"
    )
    if spec is None or spec.loader is None:
        raise RuntimeError("cannot load 11_index_providers.py")
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def _auth() -> tuple[str, str]:
    return (
        os.environ.get("NEO4J_USER", "neo4j"),
        os.environ.get("NEO4J_PASSWORD", ""),
    )


def _load_json(path: Path) -> Any:
    return json.loads(path.read_text(encoding="utf-8"))


def _provider_presence(session, case_id: str) -> dict[str, dict[str, int]]:
    rows = session.run(
        """
        MATCH (n {case_id:$case_id})
        WHERE n.provider_id IS NOT NULL
        WITH n.provider_id AS provider_id,
             count(n) AS nodes,
             count { WITH n WHERE n.name IS NOT NULL AND properties(n).value IS NOT NULL } AS facts
        RETURN provider_id, nodes, facts
        """,
        case_id=case_id,
    ).data()
    presence = {provider: {"nodes": 0, "facts": 0} for provider in PROVIDERS}
    for row in rows:
        provider = str(row["provider_id"])
        presence[provider] = {"nodes": int(row["nodes"]), "facts": int(row["facts"])}
    return presence


def _read_provider_context(session, case_id: str, provider_id: str) -> tuple[str, list[dict], int]:
    node_rows = session.run(
        """
        MATCH (n {case_id:$case_id, provider_id:$provider_id})
        WHERE n.name IS NOT NULL
          AND NOT any(label IN labels(n) WHERE label IN $infra)
        RETURN labels(n) AS labels, properties(n) AS props
        ORDER BY coalesce(n.name, '')
        LIMIT 120
        """,
        case_id=case_id,
        provider_id=provider_id,
        infra=federation.INFRA_LABELS,
    ).data()
    lines: list[str] = []
    facts: list[dict[str, Any]] = []
    for row in node_rows:
        labels = [label for label in (row["labels"] or []) if label not in INFRA]
        props = row["props"] or {}
        name = str(props.get("name") or "")
        bits = [
            f"{key}={props[key]}"
            for key in ("value", "period", "basis", "segment", "amount")
            if props.get(key)
        ]
        label = "/".join(labels) if labels else "Entity"
        lines.append(f"- ({label}) {name}" + (f" [{', '.join(bits)}]" if bits else ""))
        if props.get("value") is not None:
            facts.append(
                {
                    "metric_raw": name,
                    "value_raw": str(props.get("value")),
                    "period": str(props.get("period") or ""),
                    "basis": str(props.get("basis") or ""),
                    "eid": str(props.get("source_provider_eid") or props.get("origin_eid") or ""),
                }
            )

    rel_rows = session.run(
        """
        MATCH (a {case_id:$case_id, provider_id:$provider_id})-[r]->
              (b {case_id:$case_id, provider_id:$provider_id})
        WHERE a.name IS NOT NULL AND b.name IS NOT NULL
        RETURN coalesce(a.name, '?') AS s, type(r) AS t, coalesce(b.name, '?') AS o
        LIMIT 80
        """,
        case_id=case_id,
        provider_id=provider_id,
    ).data()
    if rel_rows:
        lines.append("--- relationships ---")
        lines.extend(f"- {row['s']} -{row['t']}-> {row['o']}" for row in rel_rows)
    context = (
        f"=== {provider_id.upper()} category DB evidence ===\n" + "\n".join(lines)
        if lines
        else ""
    )
    return context, facts, len(node_rows)


def _survive_facts(provider_facts: dict[str, list[dict[str, Any]]], ruleset) -> dict[str, Any]:
    grouped: dict[tuple[str, str, str], list[tuple[str, dict[str, Any]]]] = defaultdict(list)
    for provider_id, facts in provider_facts.items():
        for fact in facts:
            key = (
                fact["metric_raw"].strip().lower(),
                fact["period"].strip().lower(),
                fact["basis"].strip().lower(),
            )
            grouped[key].append((provider_id, fact))
    golden: list[dict[str, Any]] = []
    quarantined: list[dict[str, Any]] = []
    panel_size = max(len(provider_facts), 1)
    for (metric, period, basis), items in sorted(grouped.items()):
        outcome = survive_numeric(
            [SourceFact(source=provider_id, raw=fact["value_raw"]) for provider_id, fact in items],
            panel_size=panel_size,
            ruleset=ruleset,
        )
        label = items[0][1]["metric_raw"]
        if outcome.status == "golden":
            golden.append(
                {
                    "metric": label,
                    "period": period,
                    "basis": basis,
                    "value": outcome.value_raw,
                    "confidence": outcome.confidence,
                    "agreement": f"{outcome.agreement_count}/{outcome.sources_reporting}",
                    "rule": outcome.rule,
                    "source": outcome.source,
                }
            )
        elif outcome.status == "quarantine":
            quarantined.append(
                {
                    "metric": label,
                    "period": period,
                    "basis": basis,
                    "rule": outcome.rule,
                    "candidates": [
                        f"{provider_id}:{fact['value_raw']}" for provider_id, fact in items
                    ],
                }
            )
    return {"golden": golden, "quarantined": quarantined, "panel_size": panel_size}


def _build_evidence_bundle(
    *,
    uri: str,
    database: str,
    case_id: str,
    category_policy: dict[str, Any],
    ruleset,
) -> EvidenceBundle:
    from neo4j import GraphDatabase

    started = time.perf_counter()
    driver = GraphDatabase.driver(uri, auth=_auth())
    try:
        with driver.session(database=database) as session:
            presence = _provider_presence(session, case_id)
            selected = select_providers_for_policy(category_policy, presence)
            contexts: dict[str, str] = {}
            fact_map: dict[str, list[dict[str, Any]]] = {}
            node_counts: dict[str, int] = {}
            fact_counts: dict[str, int] = {}
            for provider_id in selected:
                context, facts, node_count = _read_provider_context(session, case_id, provider_id)
                if context.strip() or facts:
                    contexts[provider_id] = context
                    fact_map[provider_id] = facts
                    node_counts[provider_id] = node_count
                    fact_counts[provider_id] = len(facts)
    finally:
        driver.close()
    survivorship = (
        _survive_facts(fact_map, ruleset)
        if category_policy["routing_mode"]
        in {"category_db_survivorship_first", "category_db_best_provider_then_fact_union"}
        else None
    )
    context_chars = sum(len(value) for value in contexts.values())
    return EvidenceBundle(
        selected_providers=tuple(contexts),
        provider_contexts=contexts,
        provider_fact_counts=fact_counts,
        provider_node_counts=node_counts,
        survivorship=survivorship,
        context_chars=context_chars,
        retrieval_ms=(time.perf_counter() - started) * 1000,
    )


def _selector_review(
    *,
    client,
    spec,
    query: str,
    case_id: str,
    category: str,
    category_policy: dict[str, Any],
    evidence: EvidenceBundle,
) -> dict[str, Any]:
    system = (
        "You are the Graph-CoT QuerySupervisorAgent for a category-centric graph federation system. "
        "Think internally, but return compact JSON only. Choose providers only from deterministic_candidates."
    )
    user = json.dumps(
        {
            "query": query,
            "case_id": case_id,
            "category": category,
            "database": category_policy["category_database"],
            "routing_mode": category_policy["routing_mode"],
            "primary_provider": category_policy["primary_provider"],
            "provider_scores": category_policy["provider_scores"],
            "prompt_ontology_strategy": category_policy["prompt_ontology_strategy"],
            "deterministic_candidates": list(evidence.selected_providers),
            "provider_fact_counts": evidence.provider_fact_counts,
            "provider_node_counts": evidence.provider_node_counts,
            "survivorship_available": evidence.survivorship is not None,
            "return_schema": {
                "selected_providers": ["provider_id"],
                "required_evidence": ["slot"],
                "survivorship_required": True,
                "missing_slots": ["slot"],
                "rationale": "short reason without hidden chain of thought",
            },
        },
        sort_keys=True,
    )
    text = llm_io.chat_complete(
        client=client,
        model=spec.model,
        system=system,
        user=user,
        temperature=0.1,
        response_format={"type": "json_object"},
        label="category-graph-cot-selector",
        max_attempts=3,
        spec=spec,
    )
    try:
        parsed = json.loads(text)
    except json.JSONDecodeError:
        return {"error": "json_decode_failed", "raw_text": text}
    allowed = set(evidence.selected_providers)
    selected = [p for p in parsed.get("selected_providers", []) if p in allowed]
    if selected:
        parsed["selected_providers"] = selected
    else:
        parsed["selected_providers"] = list(evidence.selected_providers)
        parsed["fallback_reason"] = "llm_selector_returned_no_valid_provider"
    return parsed


def _effective_selected_providers(
    evidence: EvidenceBundle,
    category_policy: dict[str, Any],
    selector: dict[str, Any] | None,
) -> tuple[str, ...]:
    """Apply selector conservatively.

    The category policy is already the auditable routing plan.  The Graph-CoT
    selector can narrow low-overlap primary/fact-union cases, but it must not
    discard evidence for duplicate-heavy or fallback modes where the point is
    comparing provider contexts.
    """
    if not selector:
        return evidence.selected_providers
    mode = category_policy["routing_mode"]
    if mode in {"category_db_multi_provider_context", "category_db_broadcast_fallback"}:
        return evidence.selected_providers
    if selector.get("missing_slots"):
        return evidence.selected_providers
    allowed = set(evidence.selected_providers)
    selected = tuple(p for p in selector.get("selected_providers", []) if p in allowed)
    return selected or evidence.selected_providers


def _synthesize_answer(
    *,
    client,
    spec,
    query: str,
    category: str,
    category_policy: dict[str, Any],
    evidence: EvidenceBundle,
    selector: dict[str, Any] | None,
) -> tuple[str, float, str]:
    selected = _effective_selected_providers(evidence, category_policy, selector)
    selected = tuple(p for p in selected if p in evidence.provider_contexts)
    if not selected:
        return ABSTAIN_MARK, 0.0, ""
    context = "\n\n".join(evidence.provider_contexts[p] for p in selected)
    user = (
        f"Question: {query}\n\n"
        f"Category: {category}\n"
        f"Routing mode: {category_policy['routing_mode']}\n"
        f"Category database: {json.dumps(category_policy['category_database'], sort_keys=True)}\n"
        f"Selected providers: {', '.join(selected)}\n"
        "Benchmark alias rule: Treat generic issuer nodes such as Company, "
        "Registrant, or Power Generation Equipment Company as aliases for the "
        "company named in the question for this case. Use the provider graph "
        "content to answer; do not require the ticker string itself.\n"
        "Narrative rule: For qualitative risk, strategy, company-overview, "
        "governance, legal, or footnote questions, answer from entity and "
        "relationship context even when no numeric fact nodes are present. "
        "Do not require an explicit RiskFactor label if product, market, "
        "competitor, obligation, or segment relationships ground the answer.\n"
        f"Survivorship: {json.dumps(evidence.survivorship, sort_keys=True)}\n\n"
        "Provider graph context:\n\n"
        f"{context}"
    )
    system = (
        _ANSWER_SYSTEM
        + "\nYou are answering from a category-scoped federation database. "
        "Use only the supplied provider evidence. Preserve provider provenance, "
        "call out conflicts or quarantine, and say 'not in the provided context' "
        "when required evidence is missing. In this benchmark, extracted graphs "
        "may label the filing issuer generically as Company, Registrant, or a "
        "business-description node instead of the ticker in the question; do not "
        "abstain solely because the ticker string is absent when the supplied "
        "category database context clearly describes the issuer's products, "
        "markets, risks, or financial facts."
    )
    started = time.perf_counter()
    error = ""
    try:
        answer = llm_io.chat_complete(
            client=client,
            model=spec.model,
            system=system,
            user=user,
            temperature=0.0,
            label="category-fed-synth",
            max_attempts=3,
            spec=spec,
        )
    except Exception as exc:  # noqa: BLE001
        answer = ABSTAIN_MARK
        error = f"{type(exc).__name__}: {exc}"
    return answer, (time.perf_counter() - started) * 1000, error


def _lane_stats(rows: list[dict[str, Any]]) -> dict[str, Any]:
    if not rows:
        return {"n": 0, "token_f1": 0.0, "overlap": 0.0, "abstain": 0.0, "ctx_chars": 0}
    return {
        "n": len(rows),
        "token_f1": round(
            sum(row["evaluation"].get("token_f1", 0.0) for row in rows) / len(rows), 3
        ),
        "overlap": round(
            sum(row["evaluation"].get("number_overlap_ratio", 0.0) for row in rows) / len(rows),
            3,
        ),
        "abstain": round(sum(1 for row in rows if row["abstain"]) / len(rows), 3),
        "ctx_chars": int(sum(row["context_chars"] for row in rows) / len(rows)),
    }


def _compare_to_baseline(records: list[dict[str, Any]], baseline: dict[str, Any]) -> dict[str, Any]:
    current = _lane_stats(records)
    baseline_lanes = baseline.get("lanes", {})
    best_silo = max(
        (
            stats.get("token_f1", 0.0)
            for lane, stats in baseline_lanes.items()
            if lane.startswith("silo-")
        ),
        default=0.0,
    )
    return {
        "lanes": {"category-federation": current},
        "baseline_comparison": {
            "provider_db_federation_token_f1": baseline_lanes.get("federation", {}).get(
                "token_f1", 0.0
            ),
            "best_silo_token_f1": round(best_silo, 3),
            "category_federation_token_f1": current["token_f1"],
            "category_federation_ge_provider_db_federation": current["token_f1"]
            >= baseline_lanes.get("federation", {}).get("token_f1", 0.0),
            "category_federation_ge_best_silo": current["token_f1"] >= best_silo,
        },
    }


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--run-prefix", default="fedcat-single-dbms-v1")
    parser.add_argument("--category-run-prefix", default="fedcat-category-db-v1")
    parser.add_argument("--policy-run-prefix", default="",
                        help="optional run prefix to read federation_routing_policy.json from")
    parser.add_argument("--output-run-prefix", default="",
                        help="optional run prefix for category_federation_aggregate.json output")
    parser.add_argument("--synth-llm", default="mara/MiniMax-M2.7")
    parser.add_argument("--cases-per-category", type=int, default=2)
    parser.add_argument("--case-pool", choices=("stratified", "full"), default="stratified",
                        help="stratified keeps cases-per-category balance; full uses every source parquet row")
    parser.add_argument("--case-ids", default="",
                        help="optional comma-separated case id filter within the stratified source pool")
    parser.add_argument("--case-id-file", default="",
                        help="optional newline-delimited case id filter, useful for large shards")
    parser.add_argument("--limit-cases", type=int, default=0)
    parser.add_argument("--no-llm-selector", dest="llm_selector", action="store_false")
    parser.add_argument("--no-resume", dest="resume", action="store_false")
    parser.add_argument("--no-finalize", dest="finalize", action="store_false",
                        help="write partials only; skip aggregate finalization for parallel shards")
    parser.add_argument("--dry-run", action="store_true")
    args = parser.parse_args()

    bc.set_global_determinism(42)
    idx = _load_indexer()
    cases = (
        idx.load_cases_full(seed=42)
        if args.case_pool == "full"
        else idx.load_cases_8cat(n_per_cat=args.cases_per_category, seed=42)
    )
    if args.case_ids.strip():
        wanted_case_ids = {cid.strip() for cid in args.case_ids.split(",") if cid.strip()}
        cases = [case for case in cases if case["case_id"] in wanted_case_ids]
    file_case_ids = idx.load_case_id_file(args.case_id_file)
    if file_case_ids:
        cases = [case for case in cases if case["case_id"] in file_case_ids]
    if args.limit_cases:
        cases = cases[: args.limit_cases]

    base = ROOT / "outputs" / "evaluation" / "mdm_fedcat"
    policy_run_prefix = args.policy_run_prefix or args.category_run_prefix
    output_run_prefix = args.output_run_prefix or args.category_run_prefix
    policy = _load_json(base / policy_run_prefix / "federation_routing_policy.json")
    baseline = _load_json(base / args.run_prefix / "federation_aggregate.json")
    ruleset = load_ruleset()

    print(f"== category federation plan: {len(cases)} cases ==")
    for case in cases:
        cat_policy = policy["categories"][case["category"]]
        print(
            f"   {case['category']:<18} {case['case_id']} "
            f"db={cat_policy['category_database']['database']} mode={cat_policy['routing_mode']}"
        )
    if args.dry_run:
        return 0

    spec = llm_io.parse_llm_spec(args.synth_llm)
    client = llm_io.make_chat_client(spec)

    out_dir = base / output_run_prefix
    partial_dir = out_dir / "category_bench_partial"
    partial_dir.mkdir(parents=True, exist_ok=True)
    records: list[dict[str, Any]] = []

    for index, case in enumerate(cases, 1):
        name = f"category-federation_{case['case_id']}"
        partial_path = partial_dir / f"{name}.json"
        if args.resume and partial_path.is_file():
            cached = _load_json(partial_path)
            if not cached.get("error"):
                print(f">>> [{index}/{len(cases)}] {name} - SKIP")
                records.append(cached)
                continue

        cat_policy = policy["categories"][case["category"]]
        db = cat_policy["category_database"]
        evidence = _build_evidence_bundle(
            uri=db["uri"],
            database=db["database"],
            case_id=case["case_id"],
            category_policy=cat_policy,
            ruleset=ruleset,
        )
        selector: dict[str, Any] | None = None
        selector_error = ""
        selector_ms = 0.0
        if args.llm_selector and evidence.selected_providers:
            started = time.perf_counter()
            try:
                selector = _selector_review(
                    client=client,
                    spec=spec,
                    query=case["query"],
                    case_id=case["case_id"],
                    category=case["category"],
                    category_policy=cat_policy,
                    evidence=evidence,
                )
                selector_error = str(selector.get("error") or "")
            except Exception as exc:  # noqa: BLE001
                selector_error = f"{type(exc).__name__}: {exc}"
            selector_ms = (time.perf_counter() - started) * 1000

        answer, answer_ms, error = _synthesize_answer(
            client=client,
            spec=spec,
            query=case["query"],
            category=case["category"],
            category_policy=cat_policy,
            evidence=evidence,
            selector=selector,
        )
        evaluation = evaluate_both(case["expected_answer"], answer)
        record = {
            "lane": "category-federation",
            "case_id": case["case_id"],
            "slice": case["slice"],
            "category": case["category"],
            "query": case["query"],
            "answer": answer,
            "evaluation": evaluation,
            "abstain": ABSTAIN_MARK in (answer or "").lower(),
            "category_database": db,
            "routing_mode": cat_policy["routing_mode"],
            "prompt_ontology_strategy": cat_policy["prompt_ontology_strategy"],
            "selected_providers": list(evidence.selected_providers),
            "effective_selected_providers": list(
                _effective_selected_providers(evidence, cat_policy, selector)
            ),
            "selector": selector,
            "selector_error": selector_error,
            "provider_fact_counts": evidence.provider_fact_counts,
            "provider_node_counts": evidence.provider_node_counts,
            "survivorship": evidence.survivorship,
            "context_chars": evidence.context_chars,
            "retrieval_ms": round(evidence.retrieval_ms, 1),
            "selector_ms": round(selector_ms, 1),
            "answer_ms": round(answer_ms, 1),
            "llm": args.synth_llm,
            "error": error,
        }
        bc.atomic_write_json(partial_path, record)
        records.append(record)
        print(
            f">>> [{index}/{len(cases)}] {name}: "
            f"f1={evaluation['token_f1']:.3f} abstain={record['abstain']} "
            f"providers={','.join(evidence.selected_providers) or '-'}"
        )

    if not args.finalize:
        print("== shard complete; skipped aggregate finalization ==")
        return 0

    summary = _compare_to_baseline(records, baseline)
    payload = {
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "run_prefix": args.run_prefix,
        "category_run_prefix": args.category_run_prefix,
        "policy_run_prefix": policy_run_prefix,
        "output_run_prefix": output_run_prefix,
        "topology": "single_dbms_category_databases",
        "llm_selector_enabled": args.llm_selector,
        "synth_llm": args.synth_llm,
        "ruleset_version": ruleset.version,
        "n_cases": len(cases),
        **summary,
        "records": records,
    }
    bc.atomic_write_json(out_dir / "category_federation_aggregate.json", payload)
    lane = summary["lanes"]["category-federation"]
    cmp = summary["baseline_comparison"]
    print("\ncategory-federation | n | token_f1 | num_ov | abstain | ctx chars")
    print("-" * 70)
    print(
        f"category-federation | {lane['n']:>2} | {lane['token_f1']:.3f}    | "
        f"{lane['overlap']:.3f}  | {lane['abstain']:.2f}    | {lane['ctx_chars']:>9}"
    )
    print(
        "baseline comparison: "
        f"provider-db fed={cmp['provider_db_federation_token_f1']} "
        f"best-silo={cmp['best_silo_token_f1']} "
        f"category-fed={cmp['category_federation_token_f1']}"
    )
    print(f"== wrote {(out_dir / 'category_federation_aggregate.json').relative_to(ROOT)} ==")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
