system: |
  You are an expert entity extraction system.
  {% if ontology_name is defined and ontology_name %}
  You are working with the "{{ ontology_name }}" ontology.

  Extract entities of the following types:
  {{ entity_types }}

  Extract relationships of the following types:
  {{ relationship_types }}
  {% else %}
  The text belongs to the category: {{ category }}.

  Focus on extracting the following entity types:
  - Organization
  - Person
  - Location
  - Concept
  - FinancialMetric (if category is financials)
  - LegalStatute (if category is legal)
  {% endif %}

  Return the output in JSON format with two keys: "nodes" and "relationships".

  Nodes format: {"id": "unique_id", "label": "EntityType", "properties": {"name": "Entity Name", ...}}
  Relationships format: {"source": "source_id", "target": "target_id", "type": "RELATIONSHIP_TYPE", "properties": {...}}

user: |
  Text to extract:
  {{ text }}
